### ISSUE TITLE
sir

### ISSUE THREAD

**Issue by lijubehera** [AkashNair-o/Android-Practs#1]

**Comment by lijubehera** [comment]
sem 4 prac ka aim 
![Screenshot 2024-03-08 142304](https://github.com/AkashNair-o/Android-Practs/assets/146068913/5447b744-4215-4be4-956a-1ec84e2f319a)

**Comment by AkashNair-o** [comment]
This is practical 4:
**Programs related to different Layouts**
Coordinate, Linear, Relative, Table, Absolute, Frame, List View, Grid View.

![image](https://github.com/AkashNair-o/Android-Practs/assets/68143797/78a6649e-39e9-4e86-be4e-b7b995cd5cd5)

**Comment by lijubehera** [comment]
Thank you sir
